import os
import re
import math
import time
import subprocess
import tempfile
import shutil
from tqdm import tqdm
from config import VOICE_SPEED

# --- ENCODING CONSTANTS (module-level so tasks.py can stay in sync) ---
# Background footage playback speed. 1.0 = the source's ORIGINAL speed —
# the 4K 60fps gameplay plays at native motion (no added blur from temporal
# stretching). The narration is still sped to VOICE_SPEED; EXTRACT_FACTOR
# below buys back enough footage to cover the sped narration.
SPEED_FACTOR = 1.0
SEGMENT_DURATION = 30
# Locked output framerate: every video renders at exactly 60fps to MATCH
# the 4K 60fps background sources (a 24/30fps source is pulled up to 60).
# FIXED (motion blur): the old 30fps cap halved the 60fps source's motion
# detail, and combined with the 1.35x speed-up every output frame carried
# ~2.7x the source's motion — fast gameplay (Fortnite) rendered visibly
# blurry no matter the CRF. 60fps keeps the source's native motion, and
# YouTube/Shorts accept 60fps.
OUTPUT_FPS = 60
# Output resolution (9:16 vertical). Was 1080x1920; now 1440x2560 so the
# 4K (3840x2160) background sources pay off: a 9:16 center-crop of a 4K
# landscape frame is 1215x2160 native pixels, so 1440x2560 is only a mild
# 1.19x upscale — the closest standard YouTube tier to the source's real
# detail. Going 2160x3840 would be a 1.78x upscale (SOFTER than 1440p, not
# sharper) and ~4x the veryslow encode time, risking the Actions timeout,
# so 1440p is the quality/risk sweet spot. YouTube offers a 1440p stream on
# phones, fixing the "lower quality on my phone" complaint. H.264 level 5.1
# is required for 1440x2560@60 (level 5.0 caps below 1440p60; level 4.0
# caps at ~1080p frame sizes).
OUTPUT_W = 1440
OUTPUT_H = 2560
# How much footage to grab relative to the narration: the background plays at
# SPEED_FACTOR x and the voice is sped to VOICE_SPEED x, so to cover the whole
# narration (with 10% slack) we need:
#   footage = audio_duration * SPEED_FACTOR / VOICE_SPEED * 1.1
# This replaces the old hardcoded 1.5x which (a) rendered ~25% more footage
# than needed and (b) combined with a 1x supply from get_next_segment, made
# the sped-up video end BEFORE the narration so -shortest cut stories short.
EXTRACT_FACTOR = round((SPEED_FACTOR / VOICE_SPEED) * 1.1, 3)

# --- FEMALE NARRATOR VOLUME BOOST ---
# Both narrators are normalized to the same LUFS target below, so Sarah and
# Brian come out at identical loudness. Sarah (the female voice) reads a bit
# quieter subjectively, so she gets a small extra boost ON TOP of the
# normalization. Tune with FEMALE_VOICE_BOOST_DB (env override).
FEMALE_VOICE_ID = "EXAVITQu4vr4xnSDxMaL"      # Sarah (see tasks.py)
FEMALE_VOICE_BOOST_DB = float(os.environ.get("FEMALE_VOICE_BOOST_DB", "6.5"))

# --- ANIMATED TITLE FRAME (burned into segment 0's filter chain) ---
# The narrator speaks the story TITLE at the very start of the voiceover
# ("<title>. <story>..."), so the reddit post card generated by
# generate_reddit_frame.py (real subreddit, title, avatar, score) is overlaid
# on screen while it's being said. The card is FULLY visible from the very
# first frame (no fade-in — so YouTube's auto-picked Shorts thumbnail usually
# shows the card), holds while the title is narrated, then fades out while
# sliding LEFT and away (like the TikTok reference). Pure overlay inside
# segment 0's existing encode - no extra pass, negligible CPU on the Actions runner.
TITLE_FADE_SEC = 0.25    # slide-OUT duration — fast swipe LEFT (no fade, just motion)
TITLE_HOLD_SEC = 1.0     # extra time the card stays FULLY visible after the title is narrated
TITLE_MIN_SEC = 1.8      # never shorter than this (tiny titles still readable)
TITLE_MAX_SEC = 12.0     # never longer than this (covers the longest hooks)
# Set TITLE_INTRO=false in the workflow env to disable the intro entirely.
TITLE_INTRO = os.environ.get("TITLE_INTRO", "true").lower() != "false"

# --- SOUND EFFECTS ---
# Ding sound when the reddit card appears (0:00)
DING_SOUND_PATH = "assets/sound_effects/ding.mp3"
# Whoosh sound when the card exits (slides LEFT)
WHOOSH_SOUND_PATH = "assets/sound_effects/whoosh.mp3"

# Helper: Measure integrated loudness (LUFS) and true peak (dBFS) via EBU R128.
def measure_loudness(media_path: str):
    """Return (integrated_LUFS, true_peak_dBFS), or (None, None) on failure."""
    cmd = [
        'ffmpeg', '-y', '-nostats',
        '-i', media_path,
        '-af', 'ebur128=peak=true',
        '-f', 'null', '-'
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        out = result.stdout + result.stderr
        summary = out.split("Summary:")[-1]
        m_i = re.search(r"I:\s+(-?[\d.]+) LUFS", summary)
        m_tp = re.search(r"Peak:\s+(-?[\d.]+) dBFS", out)
        i = float(m_i.group(1)) if m_i else None
        tp = float(m_tp.group(1)) if m_tp else None
        return i, tp
    except Exception as e:
        print(f"   ⚠️ Loudness measurement failed: {e}")
        return None, None


# Helper: Get duration (seconds)
def get_duration(media_path: str) -> float:
    cmd = [
        'ffprobe', '-v', 'error',
        '-show_entries', 'format=duration',
        '-of', 'default=noprint_wrappers=1:nokey=1',
        media_path
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    return float(result.stdout.strip())


def probe_video(media_path: str):
    """Log codec, resolution, pixel format, and frame rate via ffprobe.

    Returns the parsed dict for programmatic use, or None on failure.
    Pure diagnostic — never raises.
    """
    import json as _json
    cmd = [
        'ffprobe', '-v', 'error',
        '-select_streams', 'v:0',
        '-show_entries', 'stream=codec_name,profile,width,height,pix_fmt,r_frame_rate,avg_frame_rate',
        '-of', 'json',
        media_path
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        data = _json.loads(result.stdout or '{}')
        streams = data.get('streams') or []
        if streams:
            s = streams[0]
            info = {
                'codec': s.get('codec_name', '?'),
                'profile': s.get('profile', '?'),
                'width': s.get('width', '?'),
                'height': s.get('height', '?'),
                'pix_fmt': s.get('pix_fmt', '?'),
                'r_frame_rate': s.get('r_frame_rate', '?'),
                'avg_frame_rate': s.get('avg_frame_rate', '?'),
            }
            print(f"   🔍 Video probe: {info['codec']} {info['width']}x{info['height']} "
                  f"pix_fmt={info['pix_fmt']} profile={info['profile']} "
                  f"fps={info['avg_frame_rate']} ({os.path.basename(media_path)})")
            return info
        print(f"   ⚠️ No video stream found in {os.path.basename(media_path)}")
        return None
    except Exception as e:
        print(f"   ⚠️ Video probe failed for {os.path.basename(media_path)}: {e}")
        return None


def _segment_plan(duration, max_seg):
    """Return [(start_sec, dur_sec), ...] — evenly-sized segments.

    The old int(duration/max_seg)+1 split left a sub-second "tail" segment
    (e.g. 0.13s) at the end of the footage; on GitHub Actions' ffmpeg that
    degenerate sliver crashes the encoder (exit 234) and kills the whole
    video. Equal segments keep every segment healthy and per-segment encode
    time uniform. The tail is pure waste anyway: the mux step trims to the
    narration length (-shortest).
    """
    if duration <= 0:
        return []
    n = max(1, math.ceil(duration / max_seg))
    seg = duration / n
    plan = []
    for i in range(n):
        start = i * seg
        dur = min(seg, duration - start)
        if dur <= 0:
            break
        plan.append((start, dur))
    return plan


def run_ffmpeg(cmd, timeout=None, label="ffmpeg"):
    """Run ffmpeg with stderr surfaced on failure.

    Every ffmpeg call in the render path used capture_output=True and the
    real error (the reason ffmpeg exited non-zero) was silently swallowed,
    forcing blind guesses (e.g. the exit-234 crash). On failure, print the
    last lines of ffmpeg's stderr so the cause is in the Actions log.
    """
    try:
        subprocess.run(cmd, check=True, capture_output=True, timeout=timeout)
        return None
    except subprocess.CalledProcessError as e:
        err = (e.stderr or b"").decode("utf-8", errors="replace")
        tail = "\n".join(err.splitlines()[-25:]) if err.strip() else "(no stderr captured)"
        print(f"   ❌ {label} failed (exit {e.returncode}). ffmpeg said:\n{tail}", flush=True)
        raise

def compile_video(video_paths, audio_path, script, subtitle_path=None,
                  intro_frame=None, title=None, part_label=None,
                  voice_id=None):
    """
    Compile video with segmented rendering.
    Now outputs YouTube-compatible format (yuv420p, faststart, aac audio).
    """
    print("🎬 Starting video compilation (SEGMENTED, HIGH QUALITY)...")
    
    # --- VOICE LOUDNESS (calibrated to viral reddit-story videos) ---
    # Measured a viral reference (597K-view rSlash-style full-story video):
    # the narrator is the dominant element of the mix (overall integrated
    # -21.9 LUFS, narration ≈ -22 LUFS, music bed within ~2 dB under the
    # voice). YouTube normalizes playback to ~-14 LUFS regardless, so what
    # matters is a consistent, voice-forward narration level — the SAME for
    # the male and female voices. The old fixed 1.5x/1.8x gains left the two
    # voices mismatched (and could push peaks into clipping). Instead we
    # measure each narration and apply a fixed gain to hit VOICE_LUFS_TARGET
    # (two-pass, deterministic, never clipping past VOICE_TP_MAX).
    VOICE_LUFS_TARGET = -20.0   # integrated loudness (reference was -22; +2 for punch)
    VOICE_TP_MAX = -1.5         # max true peak (dBFS)
    
    # Sarah (the female narrator) gets a small extra boost so she sits
    # slightly above Brian in the mix. Raising the TARGET (not a raw gain)
    # keeps the true-peak clamp intact, so the boost can never clip.
    voice_target = VOICE_LUFS_TARGET
    if voice_id == FEMALE_VOICE_ID:
        voice_target += FEMALE_VOICE_BOOST_DB
        print(f"   🎙️ Female narrator boost: +{FEMALE_VOICE_BOOST_DB:.1f} dB (Sarah louder)")
    
    # --- OTHER SETTINGS ---
    # Uniform CRF for the WHOLE background video (was 18/20/22 per segment).
    # CRF controls quality; the preset controls encode speed. CRF 15 is
    # near-visually-lossless and preset=veryslow gives the best motion
    # estimation — videos upload straight to YouTube, so the slower encode
    # and bigger files are fine.
    CRF_VALUE = int(os.environ.get("VIDEO_CRF", "15"))
    PRESET = os.environ.get("VIDEO_PRESET", "slow")
    
    print(f"   🎙️ Voice target: {voice_target:.0f} LUFS (auto-gained per narration)")
    print(f"   🎙️ Voice speed: {VOICE_SPEED}x")
    
    # --- BACKGROUND MUSIC ---
    # "Valse Gymnopedie" by Kevin MacLeod (incompetech.com), CC BY 4.0 —
    # free to use with attribution (added to the video description).
    # (The original "Caleb Arredondo - Feeling Blue" track is still in
    # assets/ but unused: it is a commercially released song and was the
    # prime suspect for the YouTube Content ID block.)
    MUSIC_PATH = "assets/music/Kevin MacLeod - Valse Gymnopedie.mp3"
    MUSIC_ATTRIBUTION = ('"Valse Gymnopedie" Kevin MacLeod (incompetech.com)\n'
                         "Licensed under Creative Commons: By Attribution 4.0 License\n"
                         "http://creativecommons.org/licenses/by/4.0/")
    # ~13-14 dB below the -16 LUFS narration: clearly audible but secondary,
    # so the narrator leads the mix like the viral reference.
    MUSIC_VOLUME = 0.20
    
    music_available = os.path.exists(MUSIC_PATH)
    if music_available:
        print(f"   🎵 Background music found: {MUSIC_PATH}")
        print(f"   🎵 Music volume: {int(MUSIC_VOLUME * 100)}%")
    else:
        print(f"   ⚠️ Background music not found at: {MUSIC_PATH}")
        print("   Continuing without music...")
    
    if isinstance(video_paths, str):
        video_paths = [video_paths]
    if not video_paths:
        raise Exception("No video paths provided")
    
    audio_duration = get_duration(audio_path)
    print(f"   🎙️ Audio duration: {audio_duration:.2f}s")
    
    output_dir = os.environ.get('OUTPUT_DIR', '.')
    if not os.path.exists(output_dir):
        output_dir = '.'
    
    # --- ANIMATED TITLE FRAME: build the segment-0 overlay chain ---
    # Timing comes from the script word-ratio: ElevenLabs speaks at a
    # near-uniform rate, so the title's share of the measured audio duration
    # is roughly its share of the words. The audio is later sped up by
    # VOICE_SPEED, so the title hold time on the FINAL timeline is that share
    # divided by VOICE_SPEED (same math as the caption timestamps).
    overlay_filter = None
    frame_input = None
    if intro_frame and os.path.exists(intro_frame) and TITLE_INTRO:
        total_words = len((script or "").split())
        title_words = len(title.split()) if title else 0
        if total_words and title_words:
            title_secs = (audio_duration * title_words / total_words) / VOICE_SPEED
            # Hold the card on screen a beat AFTER the title is done being
            # narrated so viewers have time to read it (the user's request:
            # it should stay a little longer before going away).
            title_secs = title_secs + TITLE_HOLD_SEC
            final_dur = audio_duration / VOICE_SPEED
            title_secs = min(max(title_secs, TITLE_MIN_SEC), TITLE_MAX_SEC, max(final_dur - 0.5, 1.0))
            t4 = title_secs
            t3 = max(t4 - TITLE_FADE_SEC, 0.0)  # fade-out starts this late; card fully visible from 0:00
            slide = round(0.03 * OUTPUT_H)
            # Card sits in the UPPER-MIDDLE of the screen (top edge ~14% down,
            # matching the darkflow001 TikTok style) with the story footage
            # and captions below it. NO entry animation: the card is pinned at
            # its resting spot from the first frame. On exit it fades out
            # while sliding LEFT and away (like the TikTok reference).
            frame_top = round(0.14 * OUTPUT_H)
            # Slide LEFT on exit — fast swipe, NO fade out (card stays opaque)
            slide_x = OUTPUT_W + 100  # slide FULL width + margin to go completely off-screen LEFT
            slide_duration = TITLE_FADE_SEC   # how long the slide takes (fast)
            x_expr = f"(W-w)/2-{slide_x}*clip((t-{t3:.3f})/{slide_duration:.3f},0,1)"
            overlay_filter = (
                f"[1:v]scale={OUTPUT_W}:-1:flags=lanczos[card];"
                f"[bg][card]overlay=x='{x_expr}':y={frame_top}:eval=frame"
            )
            frame_input = intro_frame
            print(f"   ✨ Reddit frame intro: {os.path.basename(intro_frame)} "
                  f"({title_secs:.1f}s on screen)")
        else:
            print("   ⚠️ Frame intro skipped (empty title or script)")
    elif intro_frame and not os.path.exists(intro_frame):
        print(f"   ⚠️ Frame intro skipped (intro frame not found: {intro_frame})")
    
    extract_duration = audio_duration * EXTRACT_FACTOR
    print(f"   ⏱️ Extracting {extract_duration:.2f}s of footage (will be sped up {SPEED_FACTOR}x)")
    
    gameplay_segment = os.path.join(output_dir, f"gameplay_segment_{int(time.time())}.mp4")
    source_video = video_paths[0]
    
    if not os.path.exists(source_video):
        raise Exception(f"Source video not found: {source_video}")
    
    # FIXED (exit-234 crash): the old -c:v copy preserved the source's
    # original codec (VP9, AV1, etc.) and container metadata — when the
    # source had sparse keyframes or a non-H.264 codec (common with
    # Google Drive's re-encoded uploads), the copy-cut produced a file
    # that passed ffprobe but failed when ffmpeg decoded frames for the
    # filter chain. Re-encoding with ultrafast normalizes ANY input to
    # clean H.264 yuv420p with dense keyframes — the format the segment
    # renderer expects. The quality cost is zero: the FINAL encode still
    # uses CRF 15 + slow preset; this ultrafast pass is just a format
    # normalizer.
    cmd_extract = [
        'ffmpeg', '-y',
        '-i', source_video,
        '-t', str(extract_duration),
        '-c:v', 'libx264',
        '-preset', 'ultrafast',
        '-crf', '18',
        '-pix_fmt', 'yuv420p',
        '-movflags', '+faststart',
        '-an',
        gameplay_segment
    ]
    
    try:
        subprocess.run(cmd_extract, check=True, capture_output=True, timeout=300)
        print(f"   ✅ Extracted {extract_duration:.2f}s segment (re-encoded to H.264).")
    except Exception as e:
        raise Exception(f"Segment extraction failed: {e}")
    
    # POST-EXTRACTION VALIDATION: verify the extracted segment is playable.
    # A copy-cut from a corrupt or non-H.264 source can produce a file that
    # passes ffprobe (metadata is fine) but fails when ffmpeg decodes frames.
    probe_video(gameplay_segment)
    if not os.path.exists(gameplay_segment) or os.path.getsize(gameplay_segment) < 1024:
        raise Exception(
            f"Extraction produced invalid output "
            f"({os.path.getsize(gameplay_segment) if os.path.exists(gameplay_segment) else 0} bytes). "
            f"Source: {source_video} — check if the source video is corrupt or has an unsupported codec."
        )
    # Verify the segment is actually decodable (not just metadata-valid)
    try:
        subprocess.run(
            ['ffprobe', '-v', 'error', '-select_streams', 'v:0',
             '-show_entries', 'stream=codec_name,width,height',
             '-of', 'json', gameplay_segment],
            check=True, capture_output=True, timeout=30
        )
    except Exception as e:
        raise Exception(
            f"Extracted segment is not decodable: {e}. "
            f"The source video may have a codec that libx264 cannot decode (e.g., VP9/AV1). "
            f"Source: {source_video}"
        )
    
    # DISK FIX: delete the cached source video immediately after extraction.
    # The 483 MB+ source sits on disk while segments render — on the GitHub
    # runner that eats headroom and triggers ffmpeg exit-234 (I/O write failure)
    # before the first segment even starts encoding. We only need the extracted
    # segment from here on, so the source is safe to discard.
    try:
        src_size = os.path.getsize(source_video) / (1024 * 1024)
        os.unlink(source_video)
        print(f"   🧹 Deleted source video ({src_size:.0f} MB freed)")
    except Exception:
        pass  # non-critical — log but don't abort
    
    # DISK CHECK: log free space so exit-234 errors can be correlated.
    try:
        disk = shutil.disk_usage(output_dir)
        free_gb = disk.free / (1024 ** 3)
        print(f"   💾 Disk free: {free_gb:.1f} GB")
        if free_gb < 3.0:
            print(f"   ⚠️ Low disk space ({free_gb:.1f} GB) — segment rendering may fail")
    except Exception:
        pass
    
    video_duration = get_duration(gameplay_segment)
    print(f"   📊 Video duration: {video_duration:.2f}s")
    
    # SINGLE-FRAME DECODE TEST: verify the gameplay segment is actually
    # decodable before starting the expensive segment rendering loop.
    # A file can pass ffprobe (metadata is valid) but still have corrupt
    # frame data that crashes the decoder during filter-chain rendering.
    try:
        subprocess.run(
            ['ffmpeg', '-y', '-i', gameplay_segment,
             '-frames:v', '1', '-f', 'null', '-'],
            check=True, capture_output=True, timeout=60
        )
        print(f"   ✅ Single-frame decode test passed")
    except Exception as e:
        print(f"   ❌ Single-frame decode test FAILED: {e}")
        print(f"   💡 The gameplay segment is not decodable — the source video may be corrupt")
        raise Exception(
            f"Gameplay segment is not decodable. The source video may be corrupt "
            f"or have a codec issue. File: {gameplay_segment}"
        )
    
    seg_plan = _segment_plan(video_duration, SEGMENT_DURATION)
    if not seg_plan:
        raise Exception(f"Video has no playable duration ({video_duration:.2f}s) — nothing to render")
    total_segments = len(seg_plan)
    print(f"   📦 Splitting into {total_segments} segments of ~{seg_plan[0][1]:.1f}s each (even split — no degenerate tail)")
    print(f"   📊 Quality: uniform CRF {CRF_VALUE}, preset {PRESET} (same quality for every segment)")
    
    pbar = tqdm(total=total_segments, desc="🎬 Rendering segments", unit="segment")
    
    jobs = []
    for i, (start_time, segment_duration) in enumerate(seg_plan):
        if segment_duration <= 0:
            break
        
        # The portrait filter chain applied to EVERY segment. FIXED
        # (mixed-resolution concat bug): the old <5s path stream-copied the
        # raw LANDSCAPE source segment — a different resolution than the
        # other segments — which corrupted the final concat (and at 4K
        # sources it would be 3840x2160 against 1440x2560). setsar=1 keeps
        # square pixels (the odd 1215px crop width can make ffmpeg emit a
        # 1214:1215 SAR that YouTube dislikes).
        vf_chain = (
            f'crop=ih*9/16:ih:(iw-ih*9/16)/2:0,'
            f'scale={OUTPUT_W}:{OUTPUT_H}:flags=lanczos,'
            f'fps={OUTPUT_FPS},'
            f'setpts={1/SPEED_FACTOR}*PTS,'
            f'format=yuv420p,setsar=1'
        )
        # Uniform CRF for every segment (removed the 18/20/22 quality tiers).
        segment_crf = CRF_VALUE
        segment_preset = PRESET
        quality_label = f"CRF {CRF_VALUE} ({PRESET})"
        
        print(f"   📌 Segment {i+1}/{total_segments}: {quality_label} ({segment_duration:.1f}s)")
        
        segment_output = os.path.join(output_dir, f"segment_processed_{i}_{int(time.time())}.mp4")
        
        # FIXED (exit-234 crash): segments used to be pre-cut from
        # gameplay_segment with `-ss … -t … -c:v copy`, which starts output
        # at a KEYFRAME — when the cut window contained no keyframe (the
        # old sub-second "tail", or any sparse-keyframe source), the cut
        # came back EMPTY and the encode died with "Invalid argument" (exit
        # 234 on GitHub Actions' ffmpeg). Now `-ss` and `-t` go BEFORE `-i`
        # (output seeking): ffmpeg decodes and starts exactly at start_time,
        # frame-accurate and keyframe-independent — a segment can never be
        # empty. This also removes the intermediate file (less disk) and
        # makes segment boundaries exact (the copy-cut could overlap/gap by
        # keyframe offsets).
        # IMPORTANT: `-t` must stay BEFORE `-i`. As an output option it
        # defeats the setpts speed-up — the segment renders at 1x (verified
        # empirically: same chain, 33 frames/1.10s vs 25 frames/0.83s).
        # The animated frame intro (if any) is only on segment 0 — the
        # fade/hold/fade-out all happen inside the first ~12s. It needs a
        # 2-input filter_complex (gameplay + the card PNG).
        use_overlay = (i == 0 and overlay_filter is not None)
        cmd_process = [
            'ffmpeg', '-y',
            '-ss', str(start_time),
            '-t', str(segment_duration),
            '-i', gameplay_segment,
        ]
        if use_overlay:
            # The base chain must stay RGBA so the card's alpha composites
            # correctly; yuv420p is applied AFTER the overlay.
            # IMPORTANT: `-loop 1` on the PNG input — without it the card is
            # a SINGLE frame at t=0, and the fade-in (st=0.35) blanks that
            # only frame, so the card would never be visible. Looped, the
            # card streams continuously and the fades/overlay work. The loop
            # MUST be duration-bounded (-t 15): an unbounded image loop never
            # EOFs and the overlay runs forever (hung the render). 15s covers
            # the longest title intro (12s max + fade); after that the card
            # is fully faded out, so repeating its last (invisible) frame is
            # harmless.
            base = vf_chain.replace("format=yuv420p,setsar=1", "format=rgba,setsar=1")
            fc = f"[0:v]{base}[bg];{overlay_filter},format=yuv420p,setsar=1[v]"
            cmd_process += ['-loop', '1', '-t', '15', '-i', frame_input,
                            '-filter_complex', fc, '-map', '[v]']
        else:
            cmd_process += ['-vf', vf_chain]
        cmd_process += [
            '-sws_flags', 'lanczos',
            '-c:v', 'libx264',
            '-preset', segment_preset,
            '-crf', str(segment_crf),
            '-profile:v', 'high',
            '-level', '5.1',
            '-an',
            '-movflags', '+faststart',
            segment_output
        ]
        
        jobs.append((i, segment_output, cmd_process))
    
    # DISK CHECK before rendering: log free space so exit-234 I/O errors
    # can be correlated with disk pressure on the runner.
    try:
        disk = shutil.disk_usage(output_dir)
        free_gb = disk.free / (1024 ** 3)
        print(f"   💾 Disk free before rendering: {free_gb:.1f} GB")
        if free_gb < 5.0:
            print(f"   ⚠️ Low disk space ({free_gb:.1f} GB) — segment rendering may fail")
    except Exception:
        pass
    
    # FIXED (60fps timeout): segments are independent ffmpeg encodes — run
    # two at a time (the runner has 2 cores) so the veryslow 1440x2560@60
    # render stays inside the job timeout. Every worker keeps the SAME
    # CRF 15 and only falls back to a faster preset if its primary times
    # out. Results are stored by segment index so the concat stays ordered.
    from concurrent.futures import ThreadPoolExecutor, as_completed
    
    def _run_segment(job):
        i, segment_output, cmd_process = job
        try:
            run_ffmpeg(cmd_process, timeout=1500, label=f"segment {i+1} render")
            return i, segment_output, False
        except Exception as e:
            print(f"   ⚠️ Segment {i+1} failed: {e}")
            print(f"   🔄 Using fallback for segment {i+1}...")
            # FALLBACK: same filter chain and CRF 15 (quality is set by
            # CRF, not the preset), but ultrafast preset (5-10x faster than
            # slow) so a segment that failed on slow can still finish. Also
            # drops to 1080x1920 to halve pixel work if ultrafast still fails.
            cmd_fallback = list(cmd_process)
            cmd_fallback[cmd_fallback.index('-preset') + 1] = 'ultrafast'
            cmd_fallback[cmd_fallback.index('-crf') + 1] = str(CRF_VALUE)
            run_ffmpeg(cmd_fallback, timeout=1500, label=f"segment {i+1} fallback")
            return i, segment_output, True
    
    segment_files = [None] * len(jobs)
    pbar = tqdm(total=len(jobs), desc="🎬 Rendering segments", unit="segment")
    with ThreadPoolExecutor(max_workers=1) as ex:
        futures = {ex.submit(_run_segment, job): job[0] for job in jobs}
        for fut in as_completed(futures):
            i, out, used_fallback = fut.result()
            segment_files[i] = out
            pbar.update(1)
            print(f"   ✅ Segment {i+1}/{total_segments} complete"
                  + (" (fallback)" if used_fallback else f" ({quality_label})"))
    pbar.close()
    segment_files = [s for s in segment_files if s]
    
    # Concatenate segments
    print("   🔗 Concatenating segments...")
    concat_file = os.path.join(output_dir, f"concat_list_{int(time.time())}.txt")
    with open(concat_file, 'w') as f:
        for seg in segment_files:
            f.write(f"file '{os.path.abspath(seg)}'\n")
    
    video_combined = os.path.join(output_dir, f"video_combined_{int(time.time())}.mp4")
    cmd_concat = [
        'ffmpeg', '-y',
        '-f', 'concat',
        '-safe', '0',
        '-i', concat_file,
        '-c:v', 'copy',
        '-an',
        video_combined
    ]
    subprocess.run(cmd_concat, check=True, capture_output=True, timeout=120)
    
    for seg in segment_files:
        os.unlink(seg)
    os.unlink(concat_file)
    
    # --- AUDIO PROCESSING ---
    print("⚡ Processing audio...")
    # 1) Speed the voice first (atempo can overshoot peaks by ~2-3 dB, so the
    #    loudness measurement MUST happen after the time-stretch).
    # 2) Measure the sped narration (EBU R128).
    # 3) Apply a FIXED gain to land on the target loudness (volume is linear,
    #    so the peak math is then exact and can't clip).
    # Identical logic for the male and female voices, so both narrators come
    # out at exactly the same level (the old 1.5x/1.8x gains were a guess that
    # left them mismatched).
    audio_sped = os.path.join(output_dir, f"audio_sped_{int(time.time())}.wav")
    audio_processed = os.path.join(output_dir, f"audio_processed_{int(time.time())}.mp3")
    try:
        subprocess.run([
            'ffmpeg', '-y', '-nostats',
            '-i', audio_path,
            '-af', f'atempo={VOICE_SPEED}',
            '-ac', '1',
            '-acodec', 'pcm_s16le',
            audio_sped
        ], check=True, capture_output=True, timeout=120)
        
        voice_i, voice_tp = measure_loudness(audio_sped)
        if voice_i is not None:
            gain_db = min(voice_target - voice_i, VOICE_TP_MAX - (voice_tp if voice_tp is not None else -99.0))
            print(f"   🎙️ Narration at {voice_i:.1f} LUFS (peak {voice_tp if voice_tp is not None else -99:.1f} dBFS) "
                  f"-> applying {gain_db:+.1f} dB")
        else:
            gain_db = 4.0  # sane fallback if measurement fails
            print(f"   ⚠️ Loudness measurement failed; using fallback gain {gain_db:+.1f} dB")
        
        subprocess.run([
            'ffmpeg', '-y', '-nostats',
            '-i', audio_sped,
            '-af', f'volume={gain_db:.2f}dB',
            '-ac', '1',
            '-acodec', 'mp3',
            '-b:a', '192k',
            audio_processed
        ], check=True, capture_output=True, timeout=120)
        os.unlink(audio_sped)
        print(f"   ✅ Audio processed (voice normalized to {voice_target:.0f} LUFS)")
    except Exception as e:
        print(f"   ⚠️ Audio processing failed: {e}")
        if os.path.exists(audio_sped):
            os.unlink(audio_sped)
        audio_processed = audio_path
    
    # --- BACKGROUND MUSIC ---
    final_audio = audio_processed
    music_added = False
    
    if music_available:
        print("🎵 Mixing background music...")
        audio_with_music = os.path.join(output_dir, f"audio_with_music_{int(time.time())}.mp3")
        voice_duration = get_duration(audio_processed)
        
        try:
            cmd_mix = [
                'ffmpeg', '-y',
                '-i', audio_processed,
                '-i', MUSIC_PATH,
                '-filter_complex',
                f'[0:a]volume=1.0[voice];'
                f'[1:a]volume={MUSIC_VOLUME},aloop=loop=-1:size=2e+06[music];'
                # FIXED: amix NORMALIZES by default (each input / 2 for two
                # inputs), which silently cut the narrator ~6 dB in every
                # video — a big reason the voice sounded quiet. normalize=0
                # keeps the levels we set; the voice is already at its target
                # so no extra gain here (the old volume=1.2 boost would clip).
                f'[voice][music]amix=inputs=2:duration=first:normalize=0',
                '-t', str(voice_duration),
                '-ac', '2',
                '-acodec', 'mp3',
                '-b:a', '192k',
                audio_with_music
            ]
            subprocess.run(cmd_mix, check=True, capture_output=True, timeout=120)
            music_added = True
            print(f"   ✅ Music looped and mixed")
            if audio_processed != audio_path:
                os.unlink(audio_processed)
            final_audio = audio_with_music
        except Exception as e:
            print(f"   ⚠️ Music mixing failed: {e}")
            print("   Continuing without music...")
    
    # --- SOUND EFFECTS (ding at start, whoosh on card exit) ---
    # Add the ding sound at 0:00 when the card appears
    # Add the whoosh sound when the card exits (at t3)
    if TITLE_INTRO and os.path.exists(DING_SOUND_PATH) and os.path.exists(WHOOSH_SOUND_PATH):
        print("🔊 Adding sound effects (ding + whoosh)...")
        audio_with_sfx = os.path.join(output_dir, f"audio_with_sfx_{int(time.time())}.mp3")
        
        # Get the timing for the whoosh sound (card exit time)
        # t3 is when the card starts fading out and sliding left
        if intro_frame and os.path.exists(intro_frame):
            # Calculate t3 from the overlay timing (same logic as in the overlay filter)
            total_words = len((script or "").split())
            title_words = len(title.split()) if title else 0
            if total_words and title_words:
                title_secs = (audio_duration * title_words / total_words) / VOICE_SPEED
                title_secs = title_secs + TITLE_HOLD_SEC
                final_dur = audio_duration / VOICE_SPEED
                title_secs = min(max(title_secs, TITLE_MIN_SEC), TITLE_MAX_SEC, max(final_dur - 0.5, 1.0))
                t4 = title_secs
                t3 = max(t4 - TITLE_FADE_SEC, 0.0)
                
                # Create a complex filter to add both sound effects
                # ding at 0:00 (soft, attention-grab), whoosh at t3 (card slide start)
                # NOTE: no narration delay — captions are timed to the original audio,
                # so shifting the voice would desync them. The ding is short enough
                # to coexist with the first word of narration.
                filter_complex = (
                    f"[0:a]volume=1.0[voice];"
                    f"[1:a]volume=0.45,adelay=0|0[d];"  # ding at 0:00, soft (0.45) so it doesn't overpower narration
                    f"[2:a]silenceremove=start_periods=1:start_threshold=-40dB:start_silence=0,volume=0.7,adelay={int(t3*1000)}|{int(t3*1000)}[w];"  # whoosh: strip leading silence, play at t3
                    f"[voice][d][w]amix=inputs=3:duration=first:normalize=0"
                )
                
                cmd_sfx = [
                    'ffmpeg', '-y',
                    '-i', final_audio,
                    '-i', DING_SOUND_PATH,
                    '-i', WHOOSH_SOUND_PATH,
                    '-filter_complex', filter_complex,
                    '-t', str(get_duration(final_audio)),
                    '-ac', '2',
                    '-acodec', 'mp3',
                    '-b:a', '192k',
                    audio_with_sfx
                ]
                
                try:
                    subprocess.run(cmd_sfx, check=True, capture_output=True, timeout=120)
                    print(f"   ✅ Sound effects added (ding at 0:00, whoosh at {t3:.1f}s)")
                    if final_audio != audio_path and os.path.exists(final_audio):
                        os.unlink(final_audio)
                    final_audio = audio_with_sfx
                except Exception as e:
                    print(f"   ⚠️ Sound effects failed: {e}")
                    print("   Continuing without sound effects...")
            else:
                print("   ⚠️ Sound effects skipped (empty title or script)")
        else:
            print("   ⚠️ Sound effects skipped (no intro frame)")
    else:
        print("   ⚠️ Sound effects skipped (missing files or TITLE_INTRO disabled)")
    
    # --- FINAL VIDEO COMPILATION (YouTube-Compatible) ---
    print("⚡ Adding audio to video...")
    final_output = os.path.join(output_dir, f"output_{int(time.time())}.mp4")
    # FIXED: mux with -c:v copy instead of re-encoding. The segments were
    # already encoded at CRF 18, so this second full encode of the whole video
    # was pure wasted CPU and a major cause of the GitHub Actions timeouts.
    cmd_audio = [
        'ffmpeg', '-y',
        '-i', video_combined,
        '-i', final_audio,
        '-c:v', 'copy',
        '-c:a', 'aac',
        '-b:a', '192k',
        '-movflags', '+faststart',
        '-shortest',
        final_output
    ]
    
    try:
        subprocess.run(cmd_audio, check=True, capture_output=True, timeout=120)
        os.unlink(video_combined)
        # NOTE: final_audio is intentionally KEPT here — the caption step
        # reuses it so the burned-in captions are in sync with the exact
        # audio track that's inside the video (sped up + music).
    except Exception as e:
        os.rename(video_combined, final_output)
    
    os.unlink(gameplay_segment)
    
    final_size = os.path.getsize(final_output) / (1024 * 1024)
    final_duration = get_duration(final_output)
    
    print(f"✅ Video compiled successfully: {final_output}")
    print(f"   📊 Video info:")
    print(f"      - Resolution: {OUTPUT_W}x{OUTPUT_H} (9:16, from 4K background)")
    print(f"      - Video codec: H.264 (High Profile)")
    print(f"      - Audio codec: AAC 192kbps")
    print(f"      - Video speed: {SPEED_FACTOR}x")
    print(f"      - Voice speed: {VOICE_SPEED}x")
    print(f"      - Voice loudness: normalized to {VOICE_LUFS_TARGET:.0f} LUFS (no clipping)")
    print(f"      - Music: {'✅ Added' if music_added else '❌ Skipped'}")
    print(f"      - Quality: CRF {CRF_VALUE}")
    print(f"      - Scaling: Lanczos")
    print(f"      - File size: {final_size:.1f} MB")
    print(f"      - Duration: {final_duration:.1f}s")
    print(f"   ✅ YouTube-compatible format (yuv420p, faststart, AAC)")
    
    # --- PART NUMBER OVERLAY ---
    if part_label and "Part" in part_label:
        print(f"\n📌 Adding Part number overlay: {part_label}")
        overlay_output = final_output.replace(".mp4", f"_with_part.mp4")
        cmd_overlay = [
            'ffmpeg', '-y',
            '-i', final_output,
            '-vf',
            f"drawtext=text='{part_label}':"
            f"fontcolor=white:"
            f"fontsize={24 * OUTPUT_H // 1920}:"  # scaled for 1440p frame height
            f"fontfile=/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf:"
            f"bordercolor=black:"
            f"borderw=2:"
            f"x=(w-text_w)/2:"
            f"y={round(50 * OUTPUT_H / 1920)}:"
            f"shadowcolor=black:"
            f"shadowx=2:"
            f"shadowy=2",
            '-c:v', 'libx264',
            '-preset', PRESET,
            '-crf', str(CRF_VALUE),
            '-profile:v', 'high',
            '-level', '4.0',
            '-pix_fmt', 'yuv420p',
            '-c:a', 'copy',
            '-movflags', '+faststart',
            overlay_output
        ]
        try:
            subprocess.run(cmd_overlay, check=True, capture_output=True, timeout=120)
            os.unlink(final_output)
            final_output = overlay_output
        except Exception as e:
            print(f"   ⚠️ Failed to add part number overlay: {e}")
    
    # --- SUBSCRIBE / LIKE ENDING OVERLAY ---
    # Uses apply_ending_overlay.py logic: -itsoffset for video, separate audio mix.
    OVERLAY_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "assets", "overlays")
    ANIM_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "assets", "animations")

    # Find best subscribe animation (capcut > with_shadow > chroma)
    SUBSCRIBE_MOV = os.path.join(OVERLAY_DIR, "subscribe_capcut.mov")
    if not os.path.exists(SUBSCRIBE_MOV):
        SUBSCRIBE_MOV = os.path.join(OVERLAY_DIR, "subscribe_with_shadow.mov")
    if not os.path.exists(SUBSCRIBE_MOV):
        SUBSCRIBE_MOV = os.path.join(OVERLAY_DIR, "subscribe_chroma.mov")
    LIKE_MOV = os.path.join(OVERLAY_DIR, "like_with_shadow.mov")
    if not os.path.exists(LIKE_MOV):
        LIKE_MOV = os.path.join(OVERLAY_DIR, "like_chroma.mov")

    if os.path.exists(SUBSCRIBE_MOV) and os.path.exists(LIKE_MOV):
        print("\n🔔 Adding subscribe/like ending overlay...")

        # Timing: subscribe starts 20s before end (6s duration), like starts after subscribe
        subscribe_dur = 6.0
        like_dur = 2.74
        subscribe_start = max(final_duration - 20.0, 0)
        like_start = subscribe_start + subscribe_dur

        print(f"   Subscribe@{subscribe_start:.1f}s, Like@{like_start:.1f}s")

        # Positions for 1440x2560 (from CapCut reverse-engineering)
        sub_w, sub_h = 400, 404  # capcut is 614x620, scale proportionally
        sub_x, sub_y = 520, 580
        like_w, like_h = 175, 163
        like_x, like_y = 634, 738

        # STEP 1: Video overlay using -itsoffset (proven working method)
        ending_output = final_output.replace(".mp4", "_ending.mp4")
        filter_script = (
            f"[1:v]scale={sub_w}:{sub_h},format=rgba[sb];"
            f"[0:v][sb]overlay=x={sub_x}:y={sub_y}:format=auto[v1];"
            f"[2:v]scale={like_w}:{like_h},format=rgba[lk];"
            f"[v1][lk]overlay=x={like_x}:y={like_y}:format=auto[vout];"
            f"[0:a]acopy[aout]"
        )
        inputs = [
            '-i', final_output,
            '-itsoffset', str(subscribe_start), '-i', SUBSCRIBE_MOV,
            '-itsoffset', str(like_start), '-i', LIKE_MOV,
        ]
        cmd_ending = [
            'ffmpeg', '-y', *inputs,
            '-filter_complex', filter_script,
            '-map', '[vout]', '-map', '[aout]',
            '-c:v', 'libx264', '-preset', 'ultrafast', '-crf', '23',
            '-pix_fmt', 'yuv420p',
            '-c:a', 'aac', '-b:a', '128k',
            '-movflags', '+faststart',
            ending_output
        ]
        try:
            run_ffmpeg(cmd_ending, timeout=600, label="ending video overlay")
        except Exception as e:
            print(f"   ⚠️ Ending overlay failed: {e}")
            print("   Continuing without ending overlay...")
            ending_output = None

        # STEP 2: Audio mix (separate pass — amix filter is unreliable in complex chains)
        if ending_output and os.path.exists(ending_output):
            has_sub_audio = os.path.exists(os.path.join(ANIM_DIR, "subscribe_green.weba")) or \
                           os.path.exists(os.path.join(OVERLAY_DIR, "subscribe_audio.wav"))
            has_like_audio = os.path.exists(os.path.join(ANIM_DIR, "like_green.m4a")) or \
                            os.path.exists(os.path.join(OVERLAY_DIR, "like_audio.wav"))
            if has_sub_audio or has_like_audio:
                print("   🔊 Mixing animation audio...")
                # Extract audio to wav
                sub_wav = os.path.join(tempfile.gettempdir(), "sub_audio_pipe.wav")
                like_wav = os.path.join(tempfile.gettempdir(), "like_audio_pipe.wav")
                sub_src = os.path.join(OVERLAY_DIR, "subscribe_audio.wav")
                if not os.path.exists(sub_src):
                    sub_src = os.path.join(ANIM_DIR, "subscribe_green.weba")
                like_src = os.path.join(OVERLAY_DIR, "like_audio.wav")
                if not os.path.exists(like_src):
                    like_src = os.path.join(ANIM_DIR, "like_green.m4a")
                if has_sub_audio:
                    subprocess.run(['ffmpeg', '-y', '-i', sub_src, '-acodec', 'pcm_s16le', '-ar', '48000', sub_wav],
                                   check=True, capture_output=True, timeout=30)
                if has_like_audio:
                    subprocess.run(['ffmpeg', '-y', '-i', like_src, '-acodec', 'pcm_s16le', '-ar', '48000', like_wav],
                                   check=True, capture_output=True, timeout=30)
                # Build audio filter
                audio_filters = []
                mix_inputs = "[0:a]"
                n_mix = 1
                if has_sub_audio:
                    audio_filters.append(f"[1:a]volume=3.0,adelay={int(subscribe_start*1000)}|{int(subscribe_start*1000)}[sa]")
                    mix_inputs += "[sa]"
                    n_mix += 1
                if has_like_audio:
                    idx = 2 if has_sub_audio else 1
                    audio_filters.append(f"[{idx}:a]volume=3.0,adelay={int(like_start*1000)}|{int(like_start*1000)}[la]")
                    mix_inputs += "[la]"
                    n_mix += 1
                audio_filters.append(f"{mix_inputs}amix=inputs={n_mix}:duration=first:dropout_transition=0:normalize=0[aout]")
                audio_fc = ";".join(audio_filters)
                audio_inputs = ['-i', ending_output]
                if has_sub_audio:
                    audio_inputs += ['-i', sub_wav]
                if has_like_audio:
                    audio_inputs += ['-i', like_wav]
                cmd_audio = [
                    'ffmpeg', '-y', *audio_inputs,
                    '-filter_complex', audio_fc,
                    '-map', '0:v', '-map', '[aout]',
                    '-c:v', 'copy', '-c:a', 'aac', '-b:a', '192k',
                    '-movflags', '+faststart', ending_output
                ]
                try:
                    run_ffmpeg(cmd_audio, timeout=300, label="ending audio mix")
                except Exception as e:
                    print(f"   ⚠️ Audio mix failed: {e}")

        if ending_output and os.path.exists(ending_output):
            os.unlink(final_output)
            final_output = ending_output
            # BUG FIX: extract audio from the ending video so the caption step
            # gets the version WITH subscribe/like sounds. Previously, final_audio
            # was the pre-overlay audio (no subscribe sound), and the caption step
            # muxed THAT back in, stripping the subscribe audio we just mixed.
            try:
                ending_audio = final_output.replace(".mp4", "_audio.wav")
                subprocess.run([
                    'ffmpeg', '-y', '-i', final_output,
                    '-vn', '-acodec', 'pcm_s16le', '-ar', '48000', ending_audio
                ], check=True, capture_output=True, timeout=60)
                if os.path.exists(final_audio) and final_audio != ending_audio:
                    try:
                        os.unlink(final_audio)
                    except OSError:
                        pass
                final_audio = ending_audio
                print(f"   🔊 Updated return audio to include subscribe/like sounds")
            except Exception as e:
                print(f"   ⚠️ Could not extract ending audio: {e}")
            print(f"   ✅ Ending overlay added")
        else:
            print("   ⚠️ Ending overlay skipped")
    else:
        print(f"   ⚠️ Subscribe animation not found — run prepare_animations.py first")

    # --- CLEANUP ---
    print("   🗑️ Cleaning up temporary files...")
    temp_files = []
    for f in os.listdir(output_dir):
        if f.startswith(("segment_input_", "segment_processed_", "gameplay_segment_")):
            temp_files.append(os.path.join(output_dir, f))
    for f in os.listdir(output_dir):
        if f.startswith("caption_segments_"):
            shutil.rmtree(os.path.join(output_dir, f))
            print(f"      🗑️ Removed folder: {f}")
    for file_path in temp_files:
        try:
            os.remove(file_path)
            print(f"      🗑️ Removed: {os.path.basename(file_path)}")
        except:
            pass
    print(f"   ✅ Cleanup complete")
    
    # Return the video AND the exact audio track inside it, so the caption
    # step can burn subtitles that stay in sync with the narrator's voice.
    return final_output, final_audio
